// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('En passant capture and promote', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('En passant capture and promote', async function() {
    await driver.get("https://www.chesslablab.com:9443/")
    await driver.manage().window().setRect({ width: 1366, height: 742 })
    await driver.findElement(By.css(".h2 > img")).click()
    await driver.findElement(By.css(".h4")).click()
    await driver.findElement(By.css(".a7 > img")).click()
    await driver.findElement(By.css(".a5")).click()
    await driver.findElement(By.css(".h4 > img")).click()
    await driver.findElement(By.css(".h5")).click()
    await driver.findElement(By.css(".g7 > img")).click()
    await driver.findElement(By.css(".g5")).click()
    await driver.findElement(By.css(".h5 > img")).click()
    await driver.findElement(By.css(".g6")).click()
    await driver.findElement(By.css(".a5 > img")).click()
    await driver.findElement(By.css(".a4")).click()
    await driver.findElement(By.css(".g6 > img")).click()
    await driver.findElement(By.css(".h7 > img")).click()
    await driver.findElement(By.css(".a4 > img")).click()
    await driver.findElement(By.css(".a3")).click()
    await driver.findElement(By.css(".h7 > img")).click()
    await driver.findElement(By.css(".g8 > img")).click()
    await driver.findElement(By.id("PawnPromotionDialog-Button-promote")).click()
    await driver.findElement(By.css(".a3 > img")).click()
    await driver.findElement(By.css(".b2 > img")).click()
    await driver.findElement(By.css(".g8 > img")).click()
    await driver.findElement(By.css(".f8 > img")).click()
    await driver.findElement(By.css(".h8 > img")).click()
    await driver.findElement(By.css(".f8 > img")).click()
  })
})
