// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Play C20 and load the PGN movetext', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Play C20 and load the PGN movetext', async function() {
    await driver.get("https://www.chesslablab.com:9443/")
    await driver.manage().window().setRect({ width: 1366, height: 742 })
    await driver.findElement(By.css(".e2 > img")).click()
    await driver.findElement(By.css(".e4")).click()
    await driver.findElement(By.css(".e7 > img")).click()
    await driver.findElement(By.css(".e5")).click()
    await driver.findElement(By.id("Buttons-copyMovetext")).click()
    await driver.findElement(By.id("Nav-analysisBoard")).click()
    await driver.findElement(By.id("Nav-analysisBoard-MenuItem-sanMovetext")).click()
    await driver.findElement(By.id("LoadSanDialog-TextField-movetext")).sendKeys("1.e4 e5")
    await driver.findElement(By.id("LoadSanDialog-Button-load")).click()
    await driver.findElement(By.css(".g1 > img")).click()
    await driver.findElement(By.css(".f3")).click()
    await driver.findElement(By.css(".b8 > img")).click()
  })
})
