// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Search A08 and continue the game', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Search A08 and continue the game', async function() {
    await driver.get("https://www.chesslablab.com:9443/")
    await driver.manage().window().setRect({ width: 1366, height: 742 })
    await driver.findElement(By.id("Nav-openingSearch")).click()
    await driver.findElement(By.id("Nav-openingSearch-MenuItem-name")).click()
    await driver.findElement(By.id("SearchNameDialog-TextField-name")).sendKeys("sicilian variation")
    await driver.findElement(By.id("SearchNameDialog-Button-search")).click()
    await driver.findElement(By.id("OpeningSearchResultTable-TableRow-1")).click()
    await driver.findElement(By.css(".d5 > img")).click()
    await driver.findElement(By.css(".e4")).click()
    await driver.findElement(By.css(".d3 > img")).click()
    await driver.findElement(By.css(".e4")).click()
    await driver.findElement(By.css(".f6 > img")).click()
    await driver.findElement(By.css(".e4")).click()
    await driver.findElement(By.css(".d2 > img")).click()
    await driver.findElement(By.css(".e4")).click()
    await driver.findElement(By.css(".d8 > img")).click()
    await driver.findElement(By.css(".d1")).click()
    await driver.findElement(By.css(".e1 > img")).click()
    await driver.findElement(By.css(".d1")).click()
  })
})
