const MAIN_BUTTON_ANALYSIS = 'analysis';
const MAIN_BUTTON_PLAY_ONLINE = 'play online';
const MAIN_BUTTON_PLAY_A_FRIEND = 'play a friend';
const MAIN_BUTTON_PLAY_COMPUTER = 'play computer';
const MAIN_BUTTON_TRAINING = 'training';
const MAIN_BUTTON_OPENING_SEARCH = 'opening search';

export {
  MAIN_BUTTON_ANALYSIS,
  MAIN_BUTTON_PLAY_ONLINE,
  MAIN_BUTTON_PLAY_A_FRIEND,
  MAIN_BUTTON_PLAY_COMPUTER,
  MAIN_BUTTON_TRAINING,
  MAIN_BUTTON_OPENING_SEARCH
};
