export default {
	CLICK_SQUARE: 'CLICK_SQUARE',
	RESET_BOARD: 'RESET_BOARD',
	GO_TO_BEGINNING_HISTORY: 'GO_TO_BEGINNING_HISTORY',
	GO_BACK_HISTORY: 'GO_BACK_HISTORY',
	GO_FORWARD_HISTORY: 'GO_FORWARD_HISTORY',
	GO_TO_END_HISTORY: 'GO_TO_END_HISTORY'
}
