const boardActionTypes = {
	START: 'START_BOARD',
	UNDO_MOVE: 'UNDO_MOVE',
	VALIDATE_MOVE: 'VALIDATE_MOVE',
	BROWSE_HISTORY: 'BROWSE_HISTORY',
	PICK_PIECE: 'PICK_PIECE',
	LEAVE_PIECE: 'LEAVE_PIECE'
};

export default boardActionTypes;
