const boardActionTypes = {
	START: 'START_BOARD',
	FLIP: 'FLIP_BOARD',
	HEURISTIC_PICTURE: 'HEURISTIC_PICTURE',
	BROWSE_HISTORY: 'BROWSE_HISTORY',
	PICK_PIECE: 'PICK_PIECE',
	LEAVE_PIECE: 'LEAVE_PIECE',
	CASTLED_SHORT: 'CASTLED_SHORT',
	CASTLED_LONG: 'CASTLED_LONG',
	LEGAL_MOVES: 'LEGAL_MOVES',
	VALID_MOVE: 'VALID_MOVE',
	PLAYFRIEND_MOVE: 'PLAYFRIEND_MOVE'
};

export default boardActionTypes;
