const modeActionTypes = {
	SET_ANALYSIS: 'SET_ANALYSIS_MODE',
	SET_LOADFEN: 'SET_LOADFEN_MODE',
	SET_PLAYFRIEND: 'SET_PLAYFRIEND_MODE',
	ACCEPT_PLAYFRIEND: 'ACCEPT_PLAYFRIEND_MODE',
	CHECKMATE: 'CHECKMATE',
	TAKEBACK_PROPOSE: 'TAKEBACK_PROPOSE',
	TAKEBACK_ACCEPT: 'TAKEBACK_ACCEPT'
};

export default modeActionTypes;
