const modeActionTypes = {
	SET_ANALYSIS: 'SET_ANALYSIS_MODE',
	SET_LOADFEN: 'SET_LOADFEN_MODE',
	SET_PLAYFRIEND: 'SET_PLAYFRIEND_MODE',
	ACCEPT_PLAYFRIEND: 'ACCEPT_PLAYFRIEND_MODE',
	CHECKMATE: 'CHECKMATE',
	TAKEBACK_PROPOSE: 'TAKEBACK_PROPOSE',
	TAKEBACK_ACCEPT: 'TAKEBACK_ACCEPT',
	DRAW_ACCEPT: 'DRAW_ACCEPT',
	DRAW_DECLINE: 'DRAW_DECLINE',
	DRAW_PROPOSE: 'DRAW_PROPOSE'
};

export default modeActionTypes;
