const serverActionTypes = {
	CONNECT: 'CONNECT_SERVER',
	CONNECTION_REQUEST: 'CONNECTION_REQUEST',
	CONNECTION_ESTABLISHED: 'CONNECTION_ESTABLISHED',
	CONNECTION_ERROR: 'CONNECTION_ERROR',
	ANALYSIS: 'START_ANALYSIS',
	PLAY_AI: 'PLAY_AI',
	PLAY_FRIEND: 'PLAY_FRIEND'
};

export default serverActionTypes;
