const serverActionTypes = {
	CONNECTION_ESTABLISHED: 'CONNECTION_ESTABLISHED',
	CONNECTION_ERROR: 'CONNECTION_ERROR',
	PLAY_AI: 'PLAY_AI',
	PLAY_FRIEND: 'PLAY_FRIEND'
};

export default serverActionTypes;
